"""new models

Revision ID: 047530a07034
Revises: 
Create Date: 2020-12-20 19:04:30.042112

"""
from alembic import op
import sqlalchemy as sa
import flask_authorize

# revision identifiers, used by Alembic.
revision = '047530a07034'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowances', flask_authorize.mixins.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubname', sa.String(length=64), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_clubname'), 'club', ['clubname'], unique=True)
    op.create_table('cord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cordname', sa.String(length=32), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('minfo_id', sa.Integer(), nullable=True),
    sa.Column('cinfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinfo_id'], ['cord.id'], ),
    sa.ForeignKeyConstraint(['minfo_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinfo_id'),
    sa.UniqueConstraint('minfo_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('cord')
    op.drop_index(op.f('ix_club_clubname'), table_name='club')
    op.drop_table('club')
    op.drop_table('role')
    op.drop_table('member')
    op.drop_table('category')
    # ### end Alembic commands ###
