"""category table

Revision ID: a1e44243c1a1
Revises: 7b93c3434bf1
Create Date: 2020-10-19 18:07:48.194636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e44243c1a1'
down_revision = '7b93c3434bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('club', sa.Column('categoryid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club', 'category', ['categoryid'], ['id'])
    op.drop_column('club', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('category', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.drop_column('club', 'categoryid')
    op.drop_table('category')
    # ### end Alembic commands ###
